# Generated by Django 6.0.2 on 2026-02-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_alter_complaint_status_alter_complaint_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='complaint_images/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
