# Generated by Django 6.0.2 on 2026-02-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('inspector', 'Inspector'), ('admin', 'Admin')], default='citizen', max_length=20),
        ),
    ]
